use super::db::{literal, query, quote_ident, Engine, QueryResult, Session};

fn cell(result: &QueryResult, row: usize, column: usize) -> String {
    result
        .rows
        .get(row)
        .and_then(|entry| entry.get(column))
        .and_then(|value| value.clone())
        .unwrap_or_default()
}

fn text(value: &str) -> String {
    literal("postgres", &Some(value.to_string()))
}

// to_regclass reads its argument as sql, so a bare User folds to user and a
// name with a dot is split into schema and table
fn regclass(name: &str) -> String {
    format!("to_regclass({})", text(&quote_ident(name)))
}

fn tick(name: &str) -> String {
    format!("`{}`", name.replace('`', "``"))
}

// postgres has no SHOW CREATE TABLE, but it will hand back exact definitions
// for types, defaults, constraints and indexes, so rebuild from those instead
// of guessing at the formatting
async fn postgres_ddl(session: &Session, table: &str) -> Result<String, String> {
    let name = quote_ident(table);
    let relation = regclass(table);

    let columns = query(
        session,
        &format!(
            "select a.attname,
                    format_type(a.atttypid, a.atttypmod),
                    a.attnotnull,
                    pg_get_expr(d.adbin, d.adrelid),
                    a.attidentity::text,
                    a.attgenerated::text
             from pg_attribute a
             left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
             where a.attrelid = {relation}::oid
               and a.attnum > 0
               and not a.attisdropped
             order by a.attnum"
        ),
    )
    .await?;

    if columns.rows.is_empty() {
        return Err("no such table".into());
    }

    let mut lines = Vec::new();

    for row in 0..columns.rows.len() {
        let mut line = format!(
            "  {} {}",
            quote_ident(&cell(&columns, row, 0)),
            cell(&columns, row, 1)
        );

        let default = cell(&columns, row, 3);

        match (
            cell(&columns, row, 4).as_str(),
            cell(&columns, row, 5).as_str(),
        ) {
            ("a", _) => line.push_str(" generated always as identity"),
            ("d", _) => line.push_str(" generated by default as identity"),
            (_, "s") => line.push_str(&format!(" generated always as ({default}) stored")),
            (_, "v") => line.push_str(&format!(" generated always as ({default}) virtual")),
            _ if !default.is_empty() => line.push_str(&format!(" default {default}")),
            _ => {}
        }

        if cell(&columns, row, 2) == "t" {
            line.push_str(" not null");
        }

        lines.push(line);
    }

    let constraints = query(
        session,
        &format!(
            "select pg_get_constraintdef(oid), conname
             from pg_constraint
             where conrelid = {relation}::oid and contype <> 'n'
             order by contype desc, conname"
        ),
    )
    .await?;

    for row in 0..constraints.rows.len() {
        lines.push(format!(
            "  constraint {} {}",
            quote_ident(&cell(&constraints, row, 1)),
            cell(&constraints, row, 0)
        ));
    }

    let mut out = format!("create table {name} (\n{}\n);", lines.join(",\n"));

    let indexes = query(
        session,
        &format!(
            "select pg_get_indexdef(i.indexrelid)
             from pg_index i
             where i.indrelid = {relation}::oid
               and not i.indisprimary
               and not exists (
                 select 1 from pg_constraint c where c.conindid = i.indexrelid
               )"
        ),
    )
    .await?;

    for row in 0..indexes.rows.len() {
        out.push_str(&format!("\n\n{};", cell(&indexes, row, 0)));
    }

    Ok(out)
}

async fn postgres_view_ddl(session: &Session, view: &str) -> Result<String, String> {
    let body = query(
        session,
        &format!("select pg_get_viewdef({}::oid, true)", regclass(view)),
    )
    .await?;

    let definition = cell(&body, 0, 0);

    if definition.is_empty() {
        return Err("no such view".into());
    }

    Ok(format!(
        "create view {} as\n{}",
        quote_ident(view),
        definition.trim()
    ))
}

async fn postgres_index_ddl(session: &Session, name: &str) -> Result<String, String> {
    let result = query(
        session,
        &format!("select pg_get_indexdef({}::oid)", regclass(name)),
    )
    .await?;

    let definition = cell(&result, 0, 0);

    if definition.is_empty() {
        return Err("no such index".into());
    }

    Ok(format!("{definition};"))
}

async fn postgres_sequence_ddl(session: &Session, name: &str) -> Result<String, String> {
    let quoted = text(name);
    let result = query(
        session,
        &format!(
            "select s.seqstart, s.seqincrement, s.seqmin, s.seqmax, s.seqcache,
                    s.seqcycle
             from pg_sequence s
             join pg_class c on c.oid = s.seqrelid
             join pg_namespace n on n.oid = c.relnamespace
             where c.relname = {quoted} and n.nspname = current_schema()"
        ),
    )
    .await?;

    if result.rows.is_empty() {
        return Err("no such sequence".into());
    }

    let cycle = if cell(&result, 0, 5) == "t" {
        " cycle"
    } else {
        ""
    };

    Ok(format!(
        "create sequence {} start with {} increment by {} minvalue {} maxvalue \
         {} cache {}{};",
        quote_ident(name),
        cell(&result, 0, 0),
        cell(&result, 0, 1),
        cell(&result, 0, 2),
        cell(&result, 0, 3),
        cell(&result, 0, 4),
        cycle
    ))
}

async fn postgres_trigger_ddl(
    session: &Session,
    name: &str,
    detail: Option<&str>,
) -> Result<String, String> {
    let quoted = text(name);
    let table = match detail {
        Some(parent) if !parent.is_empty() => format!(" and c.relname = {}", text(parent)),
        _ => String::new(),
    };

    let result = query(
        session,
        &format!(
            "select pg_get_triggerdef(t.oid)
             from pg_trigger t
             join pg_class c on c.oid = t.tgrelid
             join pg_namespace n on n.oid = c.relnamespace
             where t.tgname = {quoted} and n.nspname = current_schema(){table}
             limit 1"
        ),
    )
    .await?;

    let definition = cell(&result, 0, 0);

    if definition.is_empty() {
        return Err("no such trigger".into());
    }

    Ok(format!("{definition};"))
}

// pg_get_functiondef refuses an aggregate, and one name may carry several
// overloads, so every one of them is written out
async fn postgres_routine_ddl(session: &Session, name: &str) -> Result<String, String> {
    let result = query(
        session,
        &format!(
            "select case when p.prokind = 'a' then
                      format('create aggregate %s(%s) (sfunc = %s, stype = %s%s%s);',
                             quote_ident(p.proname),
                             pg_get_function_identity_arguments(p.oid),
                             g.aggtransfn::regproc,
                             format_type(g.aggtranstype, null),
                             case when g.aggfinalfn::oid <> 0
                                  then ', finalfunc = ' || g.aggfinalfn::regproc::text
                                  else '' end,
                             case when g.agginitval is not null
                                  then ', initcond = ' || quote_literal(g.agginitval)
                                  else '' end)
                    else pg_get_functiondef(p.oid) end
             from pg_proc p
             join pg_namespace n on n.oid = p.pronamespace
             left join pg_aggregate g on g.aggfnoid = p.oid
             where p.proname = {} and n.nspname = current_schema()
             order by p.oid",
            text(name)
        ),
    )
    .await?;

    let definitions: Vec<String> = (0..result.rows.len())
        .map(|row| cell(&result, row, 0))
        .filter(|definition| !definition.is_empty())
        .collect();

    if definitions.is_empty() {
        return Err("no such routine".into());
    }

    Ok(definitions.join("\n\n"))
}

async fn postgres_type_ddl(session: &Session, name: &str) -> Result<String, String> {
    let quoted = text(name);
    let found = query(
        session,
        &format!(
            "select t.typtype::text, t.oid
             from pg_type t
             join pg_namespace n on n.oid = t.typnamespace
             where t.typname = {quoted} and n.nspname = current_schema()"
        ),
    )
    .await?;

    let typtype = cell(&found, 0, 0);
    let oid = cell(&found, 0, 1);

    if typtype == "e" {
        let labels = query(
            session,
            &format!(
                "select enumlabel from pg_enum
                 where enumtypid = {oid}
                 order by enumsortorder"
            ),
        )
        .await?;

        let values: Vec<String> = (0..labels.rows.len())
            .map(|row| text(&cell(&labels, row, 0)))
            .collect();

        return Ok(format!(
            "create type {} as enum ({});",
            quote_ident(name),
            values.join(", ")
        ));
    }

    if typtype == "c" {
        let attributes = query(
            session,
            &format!(
                "select a.attname, format_type(a.atttypid, a.atttypmod)
                 from pg_type t
                 join pg_attribute a on a.attrelid = t.typrelid
                 where t.oid = {oid} and a.attnum > 0 and not a.attisdropped
                 order by a.attnum"
            ),
        )
        .await?;

        if attributes.rows.is_empty() {
            return Err("no definition recorded for that type".into());
        }

        let fields: Vec<String> = (0..attributes.rows.len())
            .map(|row| {
                format!(
                    "  {} {}",
                    quote_ident(&cell(&attributes, row, 0)),
                    cell(&attributes, row, 1)
                )
            })
            .collect();

        return Ok(format!(
            "create type {} as (\n{}\n);",
            quote_ident(name),
            fields.join(",\n")
        ));
    }

    if typtype.is_empty() {
        return Err("no such type".into());
    }

    Err("that kind of type has no definition".into())
}

// a view has columns in pg_attribute just like a table does, so ask what the
// object actually is before rebuilding it
async fn postgres_kind(session: &Session, name: &str) -> Result<String, String> {
    let result = query(
        session,
        &format!(
            "select relkind::text from pg_class where oid = {}::oid",
            regclass(name)
        ),
    )
    .await?;

    let kind = cell(&result, 0, 0);

    if kind.is_empty() {
        return Err("no such object".into());
    }

    Ok(kind)
}

async fn postgres_object_ddl(
    session: &Session,
    name: &str,
    kind: Option<&str>,
    detail: Option<&str>,
) -> Result<String, String> {
    match kind {
        Some("view") => postgres_view_ddl(session, name).await,
        Some("index") => postgres_index_ddl(session, name).await,
        Some("sequence") => postgres_sequence_ddl(session, name).await,
        Some("trigger") => postgres_trigger_ddl(session, name, detail).await,
        Some("routine") => postgres_routine_ddl(session, name).await,
        Some("type") => postgres_type_ddl(session, name).await,
        _ => match postgres_kind(session, name).await?.as_str() {
            "v" | "m" => postgres_view_ddl(session, name).await,
            _ => postgres_ddl(session, name).await,
        },
    }
}

async fn mysql_index_parent(session: &Session, name: &str) -> Result<String, String> {
    let quoted = literal("mysql", &Some(name.to_string()));
    let result = query(
        session,
        &format!(
            "select table_name from information_schema.statistics
             where table_schema = database() and index_name = {quoted}
             limit 1"
        ),
    )
    .await?;

    let table = cell(&result, 0, 0);

    if table.is_empty() {
        return Err("no such index".into());
    }

    Ok(table)
}

async fn mysql_routine_ddl(
    session: &Session,
    name: &str,
    detail: Option<&str>,
) -> Result<String, String> {
    let quoted = tick(name);

    match detail {
        Some(verb @ ("procedure" | "function")) => {
            let result = query(session, &format!("show create {verb} {quoted}")).await?;

            Ok(cell(&result, 0, 2))
        }
        _ => match query(session, &format!("show create procedure {quoted}")).await {
            Ok(result) => Ok(cell(&result, 0, 2)),
            Err(_) => {
                let result = query(session, &format!("show create function {quoted}")).await?;

                Ok(cell(&result, 0, 2))
            }
        },
    }
}

async fn mysql_object_ddl(
    session: &Session,
    name: &str,
    kind: Option<&str>,
    detail: Option<&str>,
) -> Result<String, String> {
    match kind {
        Some("view") => {
            let result = query(session, &format!("show create view {}", tick(name))).await?;

            Ok(cell(&result, 0, 1))
        }
        Some("trigger") => {
            let result = query(session, &format!("show create trigger {}", tick(name))).await?;

            Ok(cell(&result, 0, 2))
        }
        Some("routine") => mysql_routine_ddl(session, name, detail).await,
        Some("index") => {
            let parent = match detail {
                Some(table) if !table.is_empty() => table.to_string(),
                _ => mysql_index_parent(session, name).await?,
            };
            let result = query(session, &format!("show create table {}", tick(&parent))).await?;

            Ok(cell(&result, 0, 1))
        }
        _ => {
            let result = query(session, &format!("show create table {}", tick(name))).await?;

            Ok(cell(&result, 0, 1))
        }
    }
}

pub async fn object_ddl(
    session: &Session,
    name: &str,
    kind: Option<&str>,
    detail: Option<&str>,
) -> Result<String, String> {
    match &session.engine {
        Engine::Postgres(_) => postgres_object_ddl(session, name, kind, detail).await,
        Engine::MySql(_) => mysql_object_ddl(session, name, kind, detail).await,
        Engine::Sqlite(_) | Engine::Duck(_) => {
            let quoted = literal("sqlite", &Some(name.to_string()));
            let result = query(
                session,
                &format!("select sql from sqlite_master where name = {quoted} and sql is not null"),
            )
            .await?;

            let definition = cell(&result, 0, 0);

            if definition.is_empty() {
                return Err("no definition recorded for that object".into());
            }

            Ok(format!("{definition};"))
        }
        _ => Err("this engine does not report definitions".into()),
    }
}
